config/routes.rb
Ratebeer::Application.routes.draw do
  resources :styles

  resources :memberships do
    post 'confirm_membership', on: :member
  end

  resources :beer_clubs

  resources :users

  root 'breweries#index'

  resources :ratings, :only => [:index, :new, :create, :destroy]
  resources :beers
  resources :breweries do
    post 'toggle_activity', on: :member
  end
  resources :sessions, only: [:new, :create]
  resources :places, only: [:index, :show]

  get 'signup', to: 'users#new'
  get 'signin', to: 'sessions#new'
  delete 'signout', to: 'sessions#destroy'

  get 'beerlist', to:'beers#list'
  get 'ngbeerlist', to:'beers#nglist'
  get 'brewerylist', to:'breweries#list'
 
  post 'places', to:'places#search'

end

app/models/beer_club.rb
class BeerClub < ActiveRecord::Base
  has_many :memberships, :dependent => :destroy
  has_many :users, through: :memberships


  def confirmed_members
    memberships.collect {|membership| membership.user if membership.confirmed }.compact
  end

  def applied_members
    memberships.collect {|membership| membership.user unless membership.confirmed }.compact
  end

  def to_s
    "#{name}"
  end
end

app/controllers/beer_clubs_controller.rb
class BeerClubsController < ApplicationController
  before_action :set_beer_club, only: [:show, :edit, :update, :destroy]
  before_action :ensure_that_signed_in, except: [:index, :show]
  before_action :ensure_that_is_admin, only: [:destroy]
  
  # GET /beer_clubs
  # GET /beer_clubs.json
  def index
    @beer_clubs = BeerClub.all
  end

  # GET /beer_clubs/1
  # GET /beer_clubs/1.json
  def show
    @membership = Membership.new
    @membership.beer_club = @beer_club
  end

  # GET /beer_clubs/new
  def new
    @beer_club = BeerClub.new
  end

  # GET /beer_clubs/1/edit
  def edit
  end

  # POST /beer_clubs
  # POST /beer_clubs.json
  def create
    @beer_club = BeerClub.new(beer_club_params)
    
    respond_to do |format|
      if @beer_club.save
        Membership.create(user: current_user, beer_club: @beer_club, confirmed: true)
        format.html { redirect_to @beer_club, notice: 'Beer club was successfully created.' }
        format.json { render action: 'show', status: :created, location: @beer_club }
      else
        format.html { render action: 'new' }
        format.json { render json: @beer_club.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /beer_clubs/1
  # PATCH/PUT /beer_clubs/1.json
  def update
    respond_to do |format|
      if @beer_club.update(beer_club_params)
        format.html { redirect_to @beer_club, notice: 'Beer club was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @beer_club.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /beer_clubs/1
  # DELETE /beer_clubs/1.json
  def destroy
    @beer_club.destroy
    respond_to do |format|
      format.html { redirect_to beer_clubs_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_beer_club
      @beer_club = BeerClub.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def beer_club_params
      params.require(:beer_club).permit(:name, :string, :founded, :integer, :city, :string)
    end
end

app/helpers/beer_clubs_helper.rb
module BeerClubsHelper
  def is_member_of(beer_club)
    current_user.memberships.any? { |membership| membership.beer_club == beer_club and membership.confirmed}
  end

  def get_application(beer_club, user)
    user.memberships.each do |membership|
      return membership if membership.beer_club == beer_club and not membership.confirmed      
    end
    nil
  end

end

app/views/beer_clubs/_form.html.erb
<%= form_for(@beer_club) do |f| %>
  <% if @beer_club.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@beer_club.errors.count, "error") %> prohibited this beer_club from being saved:</h2>

      <ul>
      <% @beer_club.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :founded %><br>
    <%= f.text_field :founded %>
  </div>
  <div class="field">
    <%= f.label :city %><br>
    <%= f.text_field :city %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/beer_clubs/edit.html.erb
<h1>Editing beer_club</h1>

<%= render 'form' %>

<%= link_to 'Show', @beer_club %> |
<%= link_to 'Back', beer_clubs_path %>

app/views/beer_clubs/index.html.erb
<h1>Beer clubs</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Name</th>
      <th>Founded</th>
      <th>City</th>
    </tr>
  </thead>

  <tbody>
    <% @beer_clubs.each do |beer_club| %>
      <tr>
        <td><%= link_to beer_club.name, beer_club %></td>
        <td><%= beer_club.founded %></td>
        <td><%= beer_club.city %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Beer club', new_beer_club_path, class: "btn btn-primary" if current_user %>

app/views/beer_clubs/new.html.erb
<h1>New beer_club</h1>

<%= render 'form' %>

<%= link_to 'Back', beer_clubs_path %>

app/views/beer_clubs/show.html.erb
<p id="notice"><%= notice %></p>

<h1>
  <%= @beer_club.name %>
</h1>

<p>
  <strong>Founded:</strong>
  <%= @beer_club.founded %>
</p>

<p>
  <strong>City:</strong>
  <%= @beer_club.city %>
</p>

 <% if current_user and not is_member_of(@beer_club) %>
   <%= form_for(@membership) do |f| %>
      <%= f.hidden_field :beer_club_id %>
      <%= f.submit value:"join the club" %>
   <% end %>
<% end %>

<h2> Members </h2>
  <ul>
    <% @beer_club.confirmed_members.each do |user| %>
      <li>
        <%= link_to user.username, user_path(user.id) %>
      </li>
    <% end %>
  </ul>

<% if is_member_of(@beer_club) %>
  <h2> Outstanding applications </h2>
    <ul>
      <% @beer_club.applied_members.each do |user| %>
        <li>
          <%= link_to user.username, user_path(user.id) %>
          <%= link_to "confirm", confirm_membership_membership_path(get_application(@beer_club, user)), method: :post, class: "btn btn-primary" %>
        </li>
      <% end %>
    </ul>
<% end %>


<%= link_to 'Edit', edit_beer_club_path(@beer_club), class: "btn btn-primary" if current_user %>
<%= link_to 'Destroy', @beer_club, method: :delete, class: "btn btn-danger", data: { confirm: 'Are you sure?' } if current_user_admin? %>