config/routes.rb
Ratebeer::Application.routes.draw do
  resources :styles

  resources :memberships do
    post 'confirm_membership', on: :member
  end

  resources :beer_clubs

  resources :users

  root 'breweries#index'

  resources :ratings, :only => [:index, :new, :create, :destroy]
  resources :beers
  resources :breweries do
    post 'toggle_activity', on: :member
  end
  resources :sessions, only: [:new, :create]
  resources :places, only: [:index, :show]

  get 'signup', to: 'users#new'
  get 'signin', to: 'sessions#new'
  delete 'signout', to: 'sessions#destroy'

  get 'beerlist', to:'beers#list'
  get 'ngbeerlist', to:'beers#nglist'
  get 'brewerylist', to:'breweries#list'
 
  post 'places', to:'places#search'

end

app/models/rating.rb
class Rating < ActiveRecord::Base
	belongs_to :beer
  belongs_to :user

  validates :score, numericality: { greater_than_or_equal_to: 1,
                                    less_than_or_equal_to: 50,
                                    only_integer: true }

  scope :recent, -> (n) { order("created_at desc").limit(n) }

	def to_s
		"#{beer.name}: #{score}"
	end
end

app/controllers/ratings_controller.rb
class RatingsController < ApplicationController
	def index
		@rating_count = Rating.all.size
    @active_raters = User.active_raters 3
    @best_breweries = Brewery.top 3
    @best_beers = Beer.top 3
    @best_styles = Style.top 3
    @recent = Rating.recent 5
	end

	def new
    	@rating = Rating.new
    	@beers = Beer.all
  	end

  	def create
      if current_user.nil?
        redirect_to :back, notice: 'you need to signin to make a rating'
      else
    		@rating = Rating.create params.require(:rating).permit(:score, :beer_id)
        if @rating.save
          current_user.ratings << @rating
    		  redirect_to current_user
        else
          @beers = Beer.all
          render :new
        end
      end
  	end

  	def destroy
	    rating = Rating.find(params[:id])
	    rating.delete if current_user == rating.user
	    redirect_to :back
	end
end

app/views/ratings/index.html.erb
<p>
total number of ratings: <%= @rating_count %>
</p> 
<h2> Top rated beers </h2>
<ul>
  <% @best_beers.each do |beer| %>
    <li> <%= link_to beer, beer_path(beer) %> </li>
  <% end %>
</ul>

<h2> Top rated styles </h2>
<ul>
  <% @best_styles.each do |style| %>
    <li> <%= link_to style, style_path(style) %> </li>
  <% end %>
</ul>

<h2> Top rated breweries </h2>
<ul>
  <% @best_breweries.each do |brewery| %>
    <li> <%= link_to brewery, brewery_path(brewery) %> </li>
  <% end %>
</ul>

<h2> Most active raters</h2>
<ul>
  <% @active_raters.each do |user| %>
    <li> <%= link_to user.username, user_path(user) %> </li>
  <% end %>
</ul>

<h2> Most recent ratings </h2>
<ul>
  <% @recent.each do |rating| %>
    <li> <%= "#{rating} by " %>
         <%= link_to rating.user.username, user_path(rating.user) %>
     </li>
  <% end %>
</ul>

<%= link_to "New rating", new_rating_path, class: "btn btn-primary" if current_user %> 

app/views/ratings/new.html.erb
<h2>Create new rating</h2>

<p id="notice"> <%= notice %> </p>

<%= form_for(@rating) do |f| %>
  <% if @rating.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@rating.errors.count, "error") %> prohibited rating from being saved:</h2>

      <ul>
      <% @rating.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.select :beer_id, options_from_collection_for_select(@beers, :id, :to_s, selected: @rating.beer_id) %>
    score: <%= f.number_field :score %>
    
  <%= f.submit class:"btn btn-primary"%>

<% end %>